### ISSUE TITLE
Add more layers

### ISSUE THREAD

**Issue by ASEM000** [ASEM000/serket#1]
- [x] ConvND
- [x] MaxPoolND
- [x] Flatten
- [x] RNN,LSTM,GRU..
- [x] kmap/kscan layer
- [x] Spectral conv

**Comment by jejjohnson** [comment]
First of all, great library! I think this is the cleanest pytorch-like abstraction for jax that I've seen. 

I wanted to know what is the scope for the layers you are interested in? Some physics-informed ML layers that come to mind that I would like to implement would be:

- Neural Fields: [siren, modulated siren](https://github.com/lucidrains/siren-pytorch), [mfn](https://github.com/boschresearch/multiplicative-filter-networks), [res-mfn](https://github.com/shekshaa/ResidualMFN)
- Neural Operators: [FNO](https://github.com/zongyi-li/fourier_neural_operator), [F-FNO](https://github.com/alasdairtran/fourierflow), [U-FNO](https://github.com/gegewen/ufno), [Geo-FNO](https://github.com/zongyi-li/Geo-FNO), [A-FNO](https://github.com/NVlabs/AFNO-transformer)
- AutoDiff Differential Operators ([example](https://github.com/pnkraemer/probfindiff/blob/main/src/probfindiff/utils/autodiff.py), [example](https://github.com/ion-g-ion/PINNs/blob/main/pinns/operators.py))


There are also some non-physics specific layers but might be useful in general. Some examples include:

- Attention
- [Advanced U-Nets](https://github.com/lucidrains/x-unet)
- [DownSampling / UpSampling](https://github.com/cetmann/iunets)

In any case, I wanted to know what was your vision and scope for the project just to get an idea about what sort of contributions are you looking for.

**Comment by ASEM000** [comment]
Thank you for your kind words, @jejjohnson 

- I think Neural fields would be interesting to implement, but not a top priority for now.
- I thought about implementing `FNO` and friends before, but I am a bit short on time. I would happily merge a PR for `FNO.` 
- AutoDiff Differential Operators seem helpful; specifically, the divergence and Laplace would complement their finite difference-based counterparts in the `fd` package. How about a PR for these two under `operators.py.`
- `Attention` is on my list for the `nn` package
- The UNet variants are very relevant to my current research; I implemented some of them internally, and once I am confident with the implementation quality, I will push it to the public API under `nn.blocks`

Feel free to submit a PR, and let's discuss it from there.
